version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost/api
    networks:
      - telco-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./backend:/app
    environment:
      - DATABASE_PATH=/app/data/telco_analysis.db
      - CORS_ORIGINS=http://localhost,http://localhost:80
    networks:
      - telco-network
    restart: unless-stopped

networks:
  telco-network:
    driver: bridge

volumes:
  data: 